version: '3.7'

volumes:
  mysql_data:
    driver: local
  mysql_log:
    driver: local
  nginx_log:
    driver: local

services:
  web-server:
    image: nginx:1.15
    container_name: nginx
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_log:/var/log/nginx
      - ${ROOT}:/var/www/html
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 127.0.0.1:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

  wordpress:
    image: wordpress:4.9.8-php7.2-fpm
    container_name: wordpress
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${ROOT}:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=database # Link to database service
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
    depends_on:
      - web-server
      - database
    restart: unless-stopped